# Numpy array operations

In [20]:
import numpy as np

In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing:",arr[2:7])
print("With step:",arr[2:9:2])
print("Negative step:",arr[-2])

Basic slicing: [3 4 5 6 7]
With step: [3 5 7 9]
Negative step: 9


In [22]:
arr_2d  = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print("specific elements of the array",arr_2d[1,2])
print("entire row",arr_2d[2])
print("entire column",arr_2d[:,2])

specific elements of the array 6
entire row [7 8 9]
entire column [3 6 9]


# Sorting

In [29]:
unsorted = np.array([4,3,6,8,6,1,8,2,3,6,4,9,0,5])
print("sorted array is",np.sort(unsorted))

arr_2d_unnsorted = np.array([[5,4,3],[9,8,7],[5,6,7]])
print("sorted 2d array is",np.sort(arr_2d_unnsorted,axis=0))

sorted array is [0 1 2 3 3 4 4 5 6 6 6 8 8 9]
sorted 2d array is [[5 4 3]
 [5 6 7]
 [9 8 7]]


## Filter

In [30]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = number[number % 2 ==0]
print("number is even :",even_num)

number is even : [ 2  4  6  8 10]


# Filter with mask

In [34]:
mask = number > 5
print("number greater than 5", number[mask])

number greater than 5 [ 6  7  8  9 10]


# Fancy indexing vs np.where

In [35]:
indice = [0,2,4]
print(number[indice])

where_result = np.where(number> 5)
print("np where result",number[where_result])

[1 3 5]
np where result [ 6  7  8  9 10]


In [37]:
condition_arr = np.where(number > 5 , True ,False)
print(condition_arr)

[False False False False False  True  True  True  True  True]


# Addind & Removing data

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combine = np.concatenate((arr1,arr2))
print(combine)

arr3 = np.array([1,2,3,4,5,6,7,8,9])
deleted = np.delete(arr3,6)
print(deleted) #7 removed

[1 2 3 4 5 6]
[1 2 3 4 5 6 8 9]


# Array compatibility

In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("compability of arrays",a.shape == b.shape)

compability of arrays True


In [43]:
orignal = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((orignal,new_row))
print(with_new_row)

new_column = np.array([[7],[8]])
with_new_column = np.hstack((orignal,new_column))
print(with_new_column)


[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]
