# LEARN ABOUT NUMPY


In [2]:
import numpy as np


# creating array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


## List vs Numpy array

In [4]:
py_list = [1, 2, 3, 4, 5]
print("python list multiplication:", py_list * 2) 

py_array = np.array([1,2,3,4,5])
print("numpy array multiplication:", py_array * 2) 

python list multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
numpy array multiplication: [ 2  4  6  8 10]


# Creating array from scratch

In [5]:
zero = np.zeros((2,3))
print("Zeros Array:\n", zero)

ones = np.ones((3,4))
print("Ones Array:\n", ones)

full = np.full((3,3),5)
print("Full Array:\n", full)

random = np.random.random((2,3))
print("random array:\n",random)

sequence = np.arange(0,10,2)
print("Sequence Array:", sequence)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
random array:
 [[0.21165851 0.7215111  0.29833606]
 [0.70411654 0.74810748 0.68936559]]
Sequence Array: [0 2 4 6 8]


# vector , matrix ,tensor

In [6]:
vector = np.array([1,3,5,7])
print("vector:",vector)

matrix = np.array([[1,3,5,7],[2,4,6,8]])
print("matrix: ",matrix)

tensor = np.array([[[1,2,3],[2,4,6]],
                   [[9,7,5],[0,8,6]]])
print("tensor:",tensor)

vector: [1 3 5 7]
matrix:  [[1 3 5 7]
 [2 4 6 8]]
tensor: [[[1 2 3]
  [2 4 6]]

 [[9 7 5]
  [0 8 6]]]


# Array properties


In [7]:
arr = np.array([[1,3,5],
                [2,4,6]])
print("shape:" , arr.shape)
print("dimension:",arr.ndim)
print("size:",arr.size)
print("dtype:",arr.dtype)
print("itemsize:",arr.itemsize)
print("strides:",arr.strides)

shape: (2, 3)
dimension: 2
size: 6
dtype: int64
itemsize: 8
strides: (24, 8)


# Array reshaping


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("orgnal array is",arr)

reshaped = arr.reshape((3,4))
print("\nreshaped array is",reshaped)

flattend = arr.flatten()
print("\nflattend array is",flattend)

# ravel: (returns view, instead of copy)
raveled = arr.ravel()
print("\nraveled array is",raveled)

transposed = reshaped.T
print("\ntransposed array is",transposed) 

orgnal array is [ 1  2  3  4  5  6  7  8  9 10 11 12]

reshaped array is [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

flattend array is [ 1  2  3  4  5  6  7  8  9 10 11 12]

raveled array is [ 1  2  3  4  5  6  7  8  9 10 11 12]

transposed array is [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
